### ISSUE TITLE
You should use switch case or object literals

### ISSUE THREAD

**Issue by AlexandreUser** [MatheusCrispim/Calculadora-resitores#1]
* [  ] bug
* [  ] release
* [ ] enhance
* [  ] wont-fix
* [  ] patch
#### the file :  " Calculadora-resistores/cores_resistores.cpp " 

This file is using a lot of conditions, it's better use switch case or use a design pattern for improving the scalability of the code.

**Comment by MatheusCrispim** [comment]
Yes, the best way is to use switch case, but this is old code when I was still learning the basics of programming. As for using a design pattern, I don't think it's the best choice, as there are other more viable ways to implement it.

**Comment by AlexandreUser** [comment]
> Yes, the best way is to use switch case, but this is old code when I was still learning the basics of programming. As for using a design pattern, I don't think it's the best choice, as there are other more viable ways to implement it.

Cool bro, i would like to hug you when i come back from work. S2 XOXO
